spring.application.name=college-student-mvn
spring.datasource.url=jdbc:postgresql://localhost:5432/college_student_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
